# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ test-ga ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 8
        java-package: jdk
    - name: Prepare environment
      run: |
        java -Xmx32m -version
        ls -lah
        google-chrome-stable --version
          
    - name: Welcome to JDI
      run: |
        echo ------------------- WELCOME TO JDI ----------------------
        mvm --version

    # - name: Welcome to JDI
    #   run: |       
    #     - echo ------------------- WELCOME TO JDI ----------------------
    #     - 
